package clock
	
	rule "run"
		salience 1
		when 
			c: Clock(!(hour == 1 && second == 1 && millis == 500))
		then
			System.out.println(c);
			Thread.sleep(500);
			c.setMillis(c.getMillis() + 500);
			update(c);
	end
	
	rule "millis"
		salience 2
		when 
			c : Clock(millis == 1000);
		then
			c.setSecond(c.getSecond() + 1);
			c.setMillis(0);
			update(c);
	end
	
	rule "second"
		salience 3
		when
			c: Clock(second == 60);
		then
			c.setMinute(c.getMinute() + 1);
			c.setSecond(0);
			update(c);
	end
	
	rule "minute"
		salience 4
		when
			c: Clock(minute == 60)
		then
			c.setHour(c.getHour() + 1);
			c.setMinute(0);
			update(c);
	end